spring:
  application:
    name: ai-document-reader-backend

  #--- Security ---
  security:
    jwt:
      secret-key: "IlVaKY30Uqx7gEihF6i0BpBxeDM8c4Oe5wjm8C+KGzo="
      expiration-ms: 900000 #15 minutes in millisecond

  #----------------
  datasource:
    url: jdbc:postgresql://localhost:5432/ai_document_reader
    username: ai_user
    password: local_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

# ----------------------------------------------------
# CUSTOM APP CONFIGURATION (Root level, no indentation)
# ----------------------------------------------------
app:
  cors:
    # Uses the ENV variable in production, falls back to localhost for local dev
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200}
  storage:
      b2:
        bucket: ${B2_BUCKET_NAME}
        region: ${B2_REGION}
        endpoint: ${B2_ENDPOINT}
        key-id: ${B2_KEY_ID}
        application-key: ${B2_APPLICATION_KEY}

server:
  port: 8080