spring:
  application:
    name: ai-document-reader-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/ai_document_reader
    username: postgres
    password: springboot
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

server:
  port: 8080